# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ngramdistance-ffi}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bali"]
  s.date = %q{2012-07-06}
  s.description = %q{Provides a fast, cross-Ruby implementation of the  ngramdistance distance algorithm.}
  s.email = %q{mailbali@gmail.com}
  s.extensions = ["ext/ngramdistance/extconf.rb"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.markdown",
     "Gemfile",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "ext/ngramdistance/.gitignore",
     "ext/ngramdistance/extconf.rb",
     "ext/ngramdistance/ngramdistance.c",
     "ext/ngramdistance/ngramdistance.h",
     "ngramdistance-ffi.gemspec",
     "lib/ngramdistance.rb",
     "spec/ngramdistance_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{https://github.com/pecbali/ngramdistance-ffi}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.8.21}
  s.summary = %q{An FFI version of the ngramdistance gem.}
  s.test_files = [
    "spec/ngramdistance_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<ffi>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

